name: Prepare Release

on:
  workflow_dispatch:
    # Allows manually triggering release via
    # https://github.com/informalsystems/apalache/actions?query=workflow%3A%22Prepare+Release%22
    inputs:
      release_version:
        description: "Version (leave empty to increment patch version)"
        required: false
        default: ""
  schedule:
    # * is a special character in YAML so you have to quote this string
    # Automatically prepare a minor version release every Monday
    - cron: "* * * * 1"

jobs:
  prepare-release:
    env:
      RELEASE_VERSION: ${{ github.event.inputs.release_version }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Configure Git
        run: |
          git config --global user.name "$GITHUB_ACTOR"
          git config --global user.email "github@actions.ci"
      - name: Prepare Release
        run: |
          ./script/release-prepare.sh
